/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Apu_cafeteria_ordering_system;

import java.io.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jorda
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    
    int flg1, flg2, number;
    String name, role, total;
    
    public Payment() {
        initComponents();
    }
    
    public Payment(String n, int cn, String r){
        initComponents();
        name = n;
        number = cn;
        role = r;
    }
    
    public Payment(Double t, String n, int cn, String r){
        initComponents();
        total = String.valueOf(t);
        txtAmount.setText(total.toString());
        name = n;
        number = cn;
        role = r;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPayment = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        lblCardNo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAmount = new javax.swing.JTextArea();
        txtCardNo = new javax.swing.JTextField();
        lblFeedback = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFeedback = new javax.swing.JTextArea();
        btnComfirmPay = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblPaymentErr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPayment.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        lblPayment.setText("Payment");

        lblAmount.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblAmount.setText("Amount: ");

        lblCardNo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblCardNo.setText("Card Number: ");

        txtAmount.setColumns(20);
        txtAmount.setRows(5);
        jScrollPane1.setViewportView(txtAmount);

        txtCardNo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        lblFeedback.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblFeedback.setText("Feedback: ");

        txtFeedback.setColumns(20);
        txtFeedback.setRows(5);
        jScrollPane2.setViewportView(txtFeedback);

        btnComfirmPay.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnComfirmPay.setText("Comfirm Pay");
        btnComfirmPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComfirmPayActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblPaymentErr.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPayment, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblAmount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblFeedback)
                                .addComponent(lblCardNo))
                            .addComponent(btnBack))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPaymentErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnComfirmPay))
                            .addComponent(txtCardNo)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPayment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAmount)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardNo)
                    .addComponent(txtCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFeedback)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(btnComfirmPay))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblPaymentErr)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        Cart cr = new Cart(name,number,role);
        cr.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnComfirmPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComfirmPayActionPerformed

        try
        {
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyyMMdd");  
            LocalDateTime now = LocalDateTime.now();  
            
            date =  Integer.parseInt(now.format(dtf));
        }
        catch(Exception e)
        {
            lblPaymentErr.setText("Something wrong with getting the date, please exit");
        }
        
        try
        {
            cardno = Integer.parseInt(txtCardNo.getText().trim());
            flg1 = 1;
        }
        catch(Exception e)
        {
            lblPaymentErr.setText("Please enter a valid card number");
        }
        try
        {
            feedback = txtFeedback.getText().trim();
            flg2 = 1;
        }
        catch(Exception e)
        {
            lblPaymentErr.setText("Please enter a valid feedback");
        }
        
        File f1 = new File("Status.txt");
        //System.out.println("Status created successfully");
            
        File f2 = new File("Payment.txt");
        //System.out.println("Payment created successfully");
        
        
        
        
        if (flg1 == 1 && flg2 == 1)
        {
            String rcardno, rfeedback, rnumber, rdate;
            String status1 = "Paid";
            rcardno = String.valueOf(cardno);
            rfeedback = String.valueOf(feedback);
            rnumber = String.valueOf(number);
            rdate = String.valueOf(date);

            String[] Payment = {name,rnumber,total,rcardno,rfeedback,rdate};
            String[] Status = {name,rnumber, total, status1,rdate};
            
            int flg3 = 0;
            int flg4 = 0;
            
            try 
            {                
                int size = Payment.length;
                BufferedWriter bf = new BufferedWriter(new FileWriter("Payment.txt",true));//buffered is to speed up write
                bf.write("\n"+Payment[0]);
                for (int j = 1; j < size; j++)
                {
                    bf.write(","+Payment[j]);
                }
                bf.close();
                //lblPaymentErr.setText("Successfully recorded the payment");
                flg3 = 1;
            } 
            catch (IOException ex) 
            {
                Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try 
            {
                int size = Status.length;
                BufferedWriter bf1 = new BufferedWriter(new FileWriter("Status.txt",true));//buffered is to speed up write
                bf1.write("\n"+Status[0]);
                for (int j = 1; j < size; j++)
                {
                    bf1.write(","+Status[j]);
                }
                bf1.close();
                //lblPaymentErr.setText("Successfully recorded the status");
                flg4 = 1;
            } 
            catch (IOException ex) 
            {
                Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (flg3 == 1 & flg4 == 1)
            {
                lblPaymentErr.setText("Payment success");
            }
            else
            {
                lblPaymentErr.setText("Payment failed");
            }
            
            
            
            /*
            this.setVisible(false);
            Cart cr = new Cart(name,number,role);
            cr.setVisible(true);
            */
            

        }
        else
        {
            lblPaymentErr.setText("There is something wrong for your card number or feedback");
        }
    }//GEN-LAST:event_btnComfirmPayActionPerformed

    int cardno = 0;
    int date = 0;
    String feedback;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnComfirmPay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCardNo;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblPaymentErr;
    private javax.swing.JTextArea txtAmount;
    private javax.swing.JTextField txtCardNo;
    private javax.swing.JTextArea txtFeedback;
    // End of variables declaration//GEN-END:variables
}
